<a href="https://colab.research.google.com/github/Rashimanish/Flight_App/blob/main/Data_Collection/Data_Overview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Set Overview**

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Read dataset
df = pd.read_csv('/content/merged_flight_climate_data.csv')

In [3]:
df.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,FL_DATE,ORIGIN_AIRPORT_ID,ORIGIN,DEST_AIRPORT_ID,DEST,CRS_DEP_TIME,...,DEP_DEL15,CRS_ARR_TIME,ARR_TIME,ARR_DELAY_NEW,ARR_DEL15,Maximum temperature,Minimum temperature,Precipitation,Snowfall,Average wind speed
0,2022,1,1,1,2022-01-01,10397,ATL,11057,CLT,645,...,0.0,809,751.0,0.0,0.0,78,68,0.06,0.0,11.86
1,2022,1,1,1,2022-01-01,13204,MCO,13930,ORD,1429,...,0.0,1639,1611.0,0.0,0.0,84,65,0.00,0.0,7.61
2,2022,1,1,1,2022-01-01,13204,MCO,13930,ORD,1233,...,NaN,1436,NaN,NaN,NaN,84,65,0.00,0.0,7.61
3,2022,1,1,1,2022-01-01,13204,MCO,13930,ORD,1210,...,0.0,1419,1348.0,0.0,0.0,84,65,0.00,0.0,7.61
4,2022,1,1,1,2022-01-01,13204,MCO,13930,ORD,1117,...,0.0,1320,1303.0,0.0,0.0,84,65,0.00,0.0,7.61

In [4]:
df.tail()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,FL_DATE,ORIGIN_AIRPORT_ID,ORIGIN,DEST_AIRPORT_ID,DEST,CRS_DEP_TIME,...,DEP_DEL15,CRS_ARR_TIME,ARR_TIME,ARR_DELAY_NEW,ARR_DEL15,Maximum temperature,Minimum temperature,Precipitation,Snowfall,Average wind speed
1841161,2023,4,12,31,2023-12-31,12266,IAH,10397,ATL,1227,...,0.0,1540,1554.0,14.0,0.0,73,38,0.0,0.0,4.25
1841162,2023,4,12,31,2023-12-31,12266,IAH,10397,ATL,1426,...,0.0,1727,1701.0,0.0,0.0,73,38,0.0,0.0,4.25
1841163,2023,4,12,31,2023-12-31,12266,IAH,10397,ATL,1812,...,0.0,2115,2100.0,0.0,0.0,73,38,0.0,0.0,4.25
1841164,2023,4,12,31,2023-12-31,12266,IAH,10397,ATL,600,...,1.0,905,1242.0,217.0,1.0,73,38,0.0,0.0,4.25
1841165,2023,4,12,31,2023-12-31,14771,SFO,14747,SEA,2125,...,0.0,2344,2332.0,0.0,0.0,58,49,0.0,NaN,2.91

In [5]:
# Display a concise summary of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1841166 entries, 0 to 1841165
Data columns (total 22 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   QUARTER              int64
 2   MONTH                int64
 3   DAY_OF_MONTH         int64
 4   FL_DATE              object
 5   ORIGIN_AIRPORT_ID    int64
 6   ORIGIN               object
 7   DEST_AIRPORT_ID      int64
 8   DEST                 object
 9   CRS_DEP_TIME         int64
 10  DEP_TIME             float64
 11  DEP_DELAY_NEW        float64
 12  DEP_DEL15            float64
 13  CRS_ARR_TIME         int64
 14  ARR_TIME             float64
 15  ARR_DELAY_NEW        float64
 16  ARR_DEL15            float64
 17  Maximum temperature  int64
 18  Minimum temperature  int64
 19  Precipitation        float64
 20  Snowfall             float64
 21  Average wind speed   float64
dtypes: float64(9), int64(10), object(3)
memory usage: 309.0+ MB

In [6]:
df.shape

(1841166, 22)

In [7]:
df.columns.tolist()

['YEAR',
 'QUARTER',
 'MONTH',
 'DAY_OF_MONTH',
 'FL_DATE',
 'ORIGIN_AIRPORT_ID',
 'ORIGIN',
 'DEST_AIRPORT_ID',
 'DEST',
 'CRS_DEP_TIME',
 'DEP_TIME',
 'DEP_DELAY_NEW',
 'DEP_DEL15',
 'CRS_ARR_TIME',
 'ARR_TIME',
 'ARR_DELAY_NEW',
 'ARR_DEL15',
 'Maximum temperature',
 'Minimum temperature',
 'Precipitation',
 'Snowfall',
 'Average wind speed']

In [8]:
# summary statistics for numerical variables
df.describe().T

,count,mean,std,min,25%,50%,75%,max
YEAR,1841166.0,2022.513691,0.499813,2022.00,2022.00,2023.00,2023.00,2023.00
QUARTER,1841166.0,2.530246,1.109959,1.00,2.00,3.00,4.00,4.00
MONTH,1841166.0,6.589795,3.416785,1.00,4.00,7.00,10.00,12.00
DAY_OF_MONTH,1841166.0,15.729953,8.779038,1.00,8.00,16.00,23.00,31.00
ORIGIN_AIRPORT_ID,1841166.0,12679.088032,1323.314788,10397.00,11298.00,12889.00,13930.00,14771.00
DEST_AIRPORT_ID,1841166.0,12679.018191,1323.237935,10397.00,11298.00,12889.00,13930.00,14771.00
CRS_DEP_TIME,1841166.0,1338.512994,519.447184,1.00,900.00,1323.00,1755.00,2359.00
DEP_TIME,1809792.0,1335.061367,538.529078,1.00,857.00,1324.00,1802.00,2400.00
DEP_DELAY_NEW,1809792.0,17.598388,56.073424,0.00,0.00,0.00,13.00,3695.00
DEP_DEL15,1809792.0,0.234227,0.423515,0.00,0.00,0.00,0.00,1.00
CRS_ARR_TIME,1841166.0,1488.146428,555.540224,1.00,1058.00,1524.00,1941.00,2359.00
ARR_TIME,1808599.0,1453.288459,583.276669,1.00,1035.00,1506.00,1935.00,2400.00
ARR_DELAY_NEW,1804443.0,17.296912,55.613166,0.00,0.00,0.00,12.00,3680.00
ARR_DEL15,1804443.0,0.233156,0.422841,0.00,0.00,0.00,0.00,1.00
Maximum temperature,1841166.0,73.487072,17.490573,-6.00,62.00,74.00,87.00,119.00
Minimum temperature,1841166.0,54.764172,16.619229,-24.00,44.00,56.00,68.00,97.00
Precipitation,1841166.0,0.088586,0.326892,0.00,0.00,0.00,0.00,8.05
Snowfall,1522879.0,0.025191,0.275038,0.00,0.00,0.00,0.00,9.30
Average wind speed,1841166.0,8.326378,3.506309,1.12,5.82,7.83,10.29,30.42

In [9]:
#Unique values in categorical columns
categorical_vars = ['YEAR', 'QUARTER', 'MONTH', 'DAY_OF_MONTH', 'ORIGIN', 'DEST']
unique_values = {var: df[var].nunique() for var in categorical_vars}
unique_values_df = pd.DataFrame(list(unique_values.items()), columns=['Column', 'Unique Values'])
unique_values_df

         Column  Unique Values
0          YEAR              2
1       QUARTER              4
2         MONTH             12
3  DAY_OF_MONTH             31
4        ORIGIN             15
5          DEST             15

In [10]:
#Summary statistics for categorical variables
summary_stats = {var: df[var].value_counts() for var in categorical_vars}
summary_stats

{'YEAR': YEAR
 2023    945791
 2022    895375
 Name: count, dtype: int64,
 'QUARTER': QUARTER
 3    473505
 4    469209
 2    462799
 1    435653
 Name: count, dtype: int64,
 'MONTH': MONTH
 10    161314
 8     160191
 7     159915
 5     158219
 6     154930
 12    154451
 11    153444
 9     153399
 3     153196
 4     149650
 1     146830
 2     135627
 Name: count, dtype: int64,
 'DAY_OF_MONTH': DAY_OF_MONTH
 27    61378
 10    61371
 20    61278
 17    61216
 21    61160
 13    61109
 22    60955
 26    60925
 14    60849
 11    60797
 6     60713
 16    60662
 18    60639
 9     60636
 28    60606
 15    60584
 19    60545
 12    60505
 7     60495
 8     60366
 2     60185
 3     60164
 5     59964
 25    59890
 23    59884
 4     59855
 1     59745
 24    59160
 30    55566
 29    55474
 31    34490
 Name: count, dtype: int64,
 'ORIGIN': ORIGIN
 LAX    181671
 DEN    145222
 ORD    143608
 ATL    143430
 LAS    138918
 DFW    128611
 SFO    125210
 PHX    117580
 SEA    112757
 MCO    112216
 EWR    110230
 JFK    102807
 IAH     98122
 MIA     92795
 CLT     87989
 Name: count, dtype: int64,
 'DEST': DEST
 LAX    181742
 DEN    145169
 ORD    143574
 ATL    143435
 LAS    139085
 DFW    128587
 SFO    125210
 PHX    117463
 SEA    112736
 MCO    112212
 EWR    110166
 JFK    102804
 IAH     98101
 MIA     92823
 CLT     88059
 Name: count, dtype: int64}

# **Missing data investigation**

In [11]:
missing_data = df.isnull().sum()
missing_data

YEAR                        0
QUARTER                     0
MONTH                       0
DAY_OF_MONTH                0
FL_DATE                     0
ORIGIN_AIRPORT_ID           0
ORIGIN                      0
DEST_AIRPORT_ID             0
DEST                        0
CRS_DEP_TIME                0
DEP_TIME                31374
DEP_DELAY_NEW           31374
DEP_DEL15               31374
CRS_ARR_TIME                0
ARR_TIME                32567
ARR_DELAY_NEW           36723
ARR_DEL15               36723
Maximum temperature         0
Minimum temperature         0
Precipitation               0
Snowfall               318287
Average wind speed          0
dtype: int64

In [12]:
total_entries = len(df)
missing_data = df.isna().sum()
missing_percentage = (missing_data / total_entries) * 100
missing_percentage = missing_percentage[missing_percentage > 0]
print(missing_percentage)

DEP_TIME          1.704029
DEP_DELAY_NEW     1.704029
DEP_DEL15         1.704029
ARR_TIME          1.768825
ARR_DELAY_NEW     1.994551
ARR_DEL15         1.994551
Snowfall         17.287252
dtype: float64

# **Missing Value Treatment**

In [13]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor

In [14]:
#columns to drop rows with missing values
critical_columns = ['DEP_TIME', 'DEP_DELAY_NEW', 'DEP_DEL15', 'ARR_TIME', 'ARR_DELAY_NEW', 'ARR_DEL15']
df.dropna(subset=critical_columns, inplace=True)
df.reset_index(drop=True, inplace=True)

In [15]:
#column to be imputed
impute_cols = ['Snowfall']

#IterativeImputer with RandomForestRegressor
imputer = IterativeImputer(estimator=RandomForestRegressor(), max_iter=10, random_state=0)

#imputer to the selected column
df[impute_cols] = imputer.fit_transform(df[impute_cols])

# Save the cleaned dataframe to a CSV
df.to_csv('cleaned_data.csv', index=False)

In [16]:
cleaned_df = pd.read_csv('cleaned_data.csv')

print("Shape of the cleaned DataFrame:", cleaned_df.shape)

Shape of the cleaned DataFrame: (1804443, 22)

In [17]:
missing_dt = cleaned_df.isnull().sum()
missing_dt

YEAR                   0
QUARTER                0
MONTH                  0
DAY_OF_MONTH           0
FL_DATE                0
ORIGIN_AIRPORT_ID      0
ORIGIN                 0
DEST_AIRPORT_ID        0
DEST                   0
CRS_DEP_TIME           0
DEP_TIME               0
DEP_DELAY_NEW          0
DEP_DEL15              0
CRS_ARR_TIME           0
ARR_TIME               0
ARR_DELAY_NEW          0
ARR_DEL15              0
Maximum temperature    0
Minimum temperature    0
Precipitation          0
Snowfall               0
Average wind speed     0
dtype: int64